let questions = [];
let madl = 0;
let hiDate = { "name":'', "madl": [0,0,0,0,100,0,0,0], "material":["quran","islamic","arabic","english","math","physics","chemistry","biology"], "whoTest":[false,false,false,false,false,false,false,false] };
let superiorMessage = get_data("supMess","مصمم ومطور التطبيق / برهان الدين العذيبي <br/> شكر خاص / مستور الشوكاني");
let dataStudents = get_data("dataS",hiDate);
let material = null;
let IDSU = get_data("idSut",0);
let dataInternet = get_data("dataInternet",{});
let studentInput = $("#student-input");
let idInput = $("#id-input");
let loginPage = document.getElementById("login-page");
$("#login-btn").click(function() { const studentName = studentInput.val(); const studentId = idInput.val(); const nameWords = studentName.split(' ').filter(word => word.length > 0); let idf = false; const str = String(studentId).trim(); const regex = /^\d{4}$/; if (!regex.test(str)) { console.error("❌ الخطأ: يجب أن يكون الرقم مكونًا من 4 أرقام فقط"); idf = false } else { console.log("✅ الرقم صحيح"); idf=true } if(nameWords.length === 4 && idf) { localStorage.setItem('studentName', studentName); localStorage.setItem("idSut", studentId); showApp(studentName); showMessage("لقد دخلت بنجاح", "success"); } else { showMessage("عفواً الرجاء التاكد من ادخال الرقم التعريف أو الأسم الصحيح والتزم بالشروط ", "error"); } });
(function () { const savedName = localStorage.getItem('studentName'); const savedId = localStorage.getItem('idSut'); if(savedName && savedId) { showApp(savedName); } else { loginPage.style.display = 'flex'; } })();
function showApp(studentName) { loginPage.style.display = 'none'; $("#content-app").css({"display":'block'}); dataStudents.name = studentName; save_data(dataStudents,"dataS"); }
function openPage(type) { const home = document.getElementById("buts-s"); const page = document.getElementById("page-content"); home.classList.remove("active"); setTimeout(() => { home.style.display = "none"; page.style.display = "block"; if (type === "quran") { pageTitle(true_quran,select_quran,type); } else if (type === "islamic") { pageTitle(true_islamic,select_islamic,type); } else if (type === "arabic") { pageTitle(true_arabic,select_arabic,type); } else if (type === "english") { pageTitle(true_english,select_english,type); } else if (type === "math") { pageTitle([],[],type); } else if (type === "physics") { pageTitle(true_physics,select_physics,type); } else if (type === "chemistry") { pageTitle(true_chemistry,select_chemistry,type); } else if (type === "biology") { pageTitle(true_biology,select_biology,type); } else { return 0; } material = type; page.classList.add("active"); }, 400); }
function pageTitle(quT, quSelect,type) { let scc = null; for(ty in dataStudents.material) { if(type === dataStudents.material[ty]) { scc = dataStudents.whoTest[ty] } else if(type == "math") { showMessage("لا يوجد اختبار رياضيات بعد", "error"); goBack(); return 0 } } if(!scc) { questions[0] = quT; questions[1] = quSelect; let htmlTrue = ''; let htmlSelect =''; let i = 0; for(qusTF of quT) { if(qusTF.unit === "1") { i++; htmlTrue += `<div class="question-container"><div class="question-text"><span>${i}</span><span>${qusTF.name}</span></div><div class="options"><button type="button" class="tr${i}" onclick="correctionTrueFalse(${qusTF.index-1},'${qusTF.true}',${i})">${qusTF.true}</button><button type="button" class="fa${i}" onclick="correctionTrueFalse(${qusTF.index-1},'${qusTF.false}',${i})">${qusTF.false}</button></div></div>` } } i=0; for(select of quSelect) { if(select.unit === "1") { i++; htmlSelect += `<div class="quiz-item"><div><span>${i}</span><span>${select.name}</span></div><div><button type="button" class="sel1${i}" onclick="correctionSelect(${select.index-1},'${select.select1}',${i})">${select.select1}</button><button type="button" class="sel2${i}" onclick="correctionSelect(${select.index-1},'${select.select2}',${i})">${select.select2}</button><button type="button" class="sel3${i}" onclick="correctionSelect(${select.index-1},'${select.select3}',${i})">${select.select3}</button><button type="button" class="sel4${i}" onclick="correctionSelect(${select.index-1},'${select.select4}',${i})">${select.select4}</button></div></div>` } } $("#true-false").html(htmlTrue); $("#select").html(htmlSelect); $("#endTs").html(`<button type="submit" class="end-test" onclick="endTest()">انهاء الاختبار</button>`); htmlTrue = ""; htmlSelect = ""; } else { showMessage("عفواً لقد اختبرت هذا الاختبار", "error"); goBack() } }
let sumAnswerTrueFalse =[];
let sumAnswerSelect =[];
function correctionTrueFalse(numberQu,answer,id) { sumAnswerTrueFalse[id]={ "answer" : answer, "index" : numberQu }; if(answer === questions[0][numberQu].true) { $(".tr"+id).css({"background":"black"}); $(".fa"+id).css({"background":"linear-gradient(135deg, #4facfe, #00c6ff)"}) } else if(answer === questions[0][numberQu].false) { $(".tr"+id).css({"background":"linear-gradient(135deg, #4facfe, #00c6ff)"}); $(".fa"+id).css({"background":"black"}) } }
function correctionSelect(numberQu,answer,id,allBut) { let Q = questions[1]; sumAnswerSelect[id] = { "answer" : answer, "index" : numberQu }; if(answer == Q[numberQu].select1) { styleSelect(id,"sel1","sel2","sel3","sel4") } else if(answer == Q[numberQu].select2) { styleSelect(id,"sel2","sel1","sel3","sel4") } else if(answer == Q[numberQu].select3) { styleSelect(id,"sel3","sel2","sel1","sel4") } else if(answer == Q[numberQu].select4) { styleSelect(id,"sel4","sel2","sel3","sel1") } }
function styleSelect(num,claName1,claName2,claName3,claName4) { let BLACK = "black"; let COLOR = "linear-gradient(135deg, #4facfe, #00c6ff)"; $("."+claName1+num).css({"background":BLACK}); $("."+claName2+num).css({"background":COLOR}); $("."+claName3+num).css({"background":COLOR}); $("."+claName4+num).css({"background":COLOR}) }
function endTest() { let beforeClearingTF = clearing(sumAnswerTrueFalse); let beforeClearingSelect = clearing(sumAnswerSelect); goTo("page2"); let htmlTrue =''; let htmlSelect =''; let i = 0; for(beforeOn of beforeClearingTF) { i++; let quTrueFales = questions[0]; let quAll = quTrueFales[beforeOn.index]; htmlTrue += `<div class="question-card vip ${beforeOn.answer === quAll.Answer ?'correct':'wrong'}"><div class="question-header"><span class="question-number">${beforeOn.index+1}</span><span class="question-text">${quAll.name}</span></div><div class="answer-box"><span class="answer-label">إجابتك</span><span class="answer-value">${beforeOn.answer}</span></div></div>`; if(beforeOn.answer === quAll.Answer) { madl += 2 } } i = 0; for(beforeSe of beforeClearingSelect) { i++; let quTrueFales = questions[1]; let quAll = quTrueFales[beforeSe.index]; htmlSelect += `<div class="question-card vip ${beforeSe.answer === quAll.Answer ?'correct':'wrong'}"><div class="question-header"><span class="question-number">${beforeSe.index+1}</span><span class="question-text">${quAll.name}</span></div><div>99</div><div class="answer-box"><span class="answer-label">إجابتك</span><span class="answer-value">${beforeSe.answer}</span></div></div>`; if(beforeSe.answer === quAll.Answer) { madl += 2 } } let df = dataStudents.material; for(d1 in df) { if(dataStudents.material[d1] === material) { dataStudents.madl[d1] = madl; dataStudents.whoTest[d1]= true } } setScore(madl); madl = 0; save_data(dataStudents,"dataS"); sumAnswerTrueFalse=[]; sumAnswerSelect=[]; $("#trueAnswer").html(htmlTrue); $("#selectAnswer").html(htmlSelect) }
function clearing(element) { let QUAN =[]; for(sum of element) { if(sum !== undefined) { QUAN.push(sum) } } return QUAN }
function goBack() { const home = document.getElementById("buts-s"); $("#updateQu").css({"display":"none"}); $(".page").removeClass("active"); setTimeout(() => { $(".page").hide(); home.style.display = "grid"; home.classList.add("active") }, 400); }
function myAccount() { goTo("myAccount"); let student = dataStudents; let materialTimer = student.material; let madlTimer = 0; for(index in materialTimer) { let madlSingle = student.madl[index]; let y = Number(index)+1; if(madlSingle <= 49) { styleMadl("elem",y,"high","medium","low") } else if(madlSingle >= 50 && madlSingle <=69) { styleMadl("elem",y,"high","low","medium") } else if(madlSingle <= 100) { styleMadl("elem",y,"medium","low","high") } madlTimer += madlSingle; $("#elem"+y).html(student.madl[index]+"%") } if(madlTimer <= 49) { styleMadl("styleMadl",'',"high","medium","low") } else if(madlTimer >= 50 && madlTimer <= 69) { styleMadl("styleMadl",'',"high","low","medium") } else if(madlTimer <= 100) { styleMadl("styleMadl",'',"medium","low","high") } $("#nameStudent").html(student.name); $("#styleMadl").html((Math.floor(madlTimer/8 * 100)/100)+"%") }
function styleMadl(nameId,y,hi,me,lo) { $("#"+nameId+y).removeClass(hi); $("#"+nameId+y).removeClass(me); $("#"+nameId+y).addClass(lo) }
function internet() { goTo("internet"); updateStatus(); window.addEventListener("offline", updateStatus); window.addEventListener("online", updateStatus); let htmlIn =''; if(dataInternet[0] == undefined) {} else { let _arryNew = orderArray(dataInternet); for(dataIn of _arryNew) { htmlIn+= `<div id="q${dataIn.madl}" class="student-card-pro ${styleMadlTop((dataIn.madl)/8)}"><div class="student-name">${dataIn.name}</div><div class="student-stats"><div class="stat"><span class="title">الترتيب</span><span class="value rank">${dataIn.order}</span></div><div class="stat"><span class="title">المعدل</span><span class="value score">${(Math.floor(dataIn.madl/8 * 100)/100)}%</span></div></div></div>` } superiorMessage = `🏆${_arryNew[0].name} / ${_arryNew[0].order} / %${Math.floor(_arryNew[0].madl/8 * 100)/100}🏆`; save_data(superiorMessage,"supMess"); updateMarqueeText(superiorMessage); $("#qutstandingTemplate").html(htmlIn) } }
function orderArray(element) { let arryNew =[]; for(elme of element) { if(elme.data.name == "") { continue } let mad = 0; for(m of elme.data.madl) { mad +=m } let jsonX ={"name":elme.data.name,"madl":mad,order:""}; arryNew.push(jsonX) } arryNew.sort((a, b) => b.madl - a.madl); let day =["الأول","الثاني","الثالث","الرابع","الخامس"]; for(arr in arryNew) { if(arr < 5) { arryNew[arr].order = day[arr] } else { arryNew[arr].order = "❌" } } return arryNew }
function styleMadlTop(index) { let h =["card-low","card-medium","card-success"]; if(index < 50) { return h[0] } else if(index < 70) { return h[1] } else if(index < 100) { return h[2] } }
function goTo(pageId) { $(".page").removeClass("active"); setTimeout(() => { if(pageId == "internet") { $("#updateQu").css({"display":"block"}) } else { $("#updateQu").css({"display":"none"}) } $(".page").css({"display":"none"}); $("#"+pageId).css({"display":"block"}).addClass("active") }, 300); }
function save_data(data,name) { let save = JSON.stringify(data); localStorage.setItem(name,save); return save }
function get_data(name,type) { let getsave =JSON.parse(localStorage.getItem(name)); if ( getsave == null) { getsave = type } return getsave }
document.querySelectorAll(".student-card-pro").forEach(card => { const score =85; if (score >= 85) { card.classList.add("card-success") } else if (score >= 60) { card.classList.add("card-medium") } else { card.classList.add("card-low") } });
function updateStatus() { const indicator = document.getElementById("net-indicator"); if (navigator.onLine) { indicator.classList.remove("offline"); indicator.classList.add("online"); $("#alertInternet").html() } else { indicator.classList.remove("online"); indicator.classList.add("offline"); $("#alertInternet").html("<div style='color: red;'>انت لست متصلاً </div>") } }
const BIN_ID = "696278a2ae596e708fd2d906";
const API_KEY = "$2a$10$.9h2pvplF6w9HT12s7BAmejJ9LC8I9C/NGw.jd9Lu4BRRBjxTusrC";
const API_URL = `https://api.jsonbin.io/v3/b/${BIN_ID}`;
async function getAll() { const res = await fetch(`${API_URL}/latest`, { headers: { "X-Master-Key": API_KEY } }); const json = await res.json(); return json.record.data || [] }
function uniqueByNameNumId(arr) { const map = new Map(); for (const item of arr) { const key = `${item.name}|${item.numId}`; map.set(key, item) } return Array.from(map.values()) }
async function addWithCheck(newItem) { let data = await getAll(); data.push(newItem); data = uniqueByNameNumId(data); await fetch(API_URL, { method: "PUT", headers: { "Content-Type": "application/json", "X-Master-Key": API_KEY }, body: JSON.stringify({ data }) }); }
async function updateByNameNumId(name, numId, newData) { let data = await getAll(); const index = data.findIndex( x => x.name === name && x.numId === numId ); if (index === -1) { return } data[index] = { ...data[index], ...newData }; data = uniqueByNameNumId(data); await fetch(API_URL, { method: "PUT", headers: { "Content-Type": "application/json", "X-Master-Key": API_KEY }, body: JSON.stringify({ data }) }); }
function mainInternet() { document.querySelector("#updateQu").style.display = "none"; (async () => { await addWithCheck({ name: dataStudents.name ,password:0, numId: 1+IDSU ,data: dataStudents}); updateByNameNumId(dataStudents.name,IDSU,{name: dataStudents.name ,numId: IDSU ,data: dataStudents}); dataInternet = await getAll(); save_data(dataInternet,"dataInternet"); $("#updateQu").css({"display":"block"}); internet() })() }
function refreshData() { mainInternet() }
function setScore(percent) { const circle = document.querySelector(".score-circle"); const text = document.querySelector(".score-circle span"); let colorGR = "4caf50"; if(percent < 50) { colorGR = "FF2A00" } text.style.color = "#"+colorGR; circle.style.background = `conic-gradient( #${colorGR} 0% ${percent}%, #e0e0e0 ${percent}% 100% )`; text.textContent = percent + "%" }
function showMessage(message, type = "success") { const container = document.getElementById("app-toast"); container.innerHTML = ""; const toast = document.createElement("div"); toast.className = `toast ${type}`; const icon = type === "success" ? "✔️" : "❌"; toast.innerHTML = ` <span class="icon">${icon}</span> <span>${message}</span> `; container.appendChild(toast); setTimeout(() => { toast.style.opacity = "0"; setTimeout(() => container.innerHTML = "", 300) }, 2500) }
function author(){ goTo("author") }
function updateMarqueeText(newText) { const track = document.getElementById("marqueeTrack"); const text1 = document.getElementById("marqueeText"); const text2 = document.getElementById("marqueeTextClone"); track.style.animation = "none"; text1.innerHTML = newText; text2.innerHTML = newText; void track.offsetWidth; track.style.animation = "marquee 15s linear infinite" }
(async () => { let dr = await getAll(); let u = orderArray(dr); if(u.length != 0){ superiorMessage = `🏆${u[0].name} / ${u[0].order} / %${Math.floor(u[0].madl/8 * 100)/100}🏆`; save_data(superiorMessage,"supMess"); updateMarqueeText(superiorMessage) } })();
updateMarqueeText(superiorMessage);
